---
- name: add gust config to sites-available
  template: src=gust.j2 dest=/etc/nginx/sites-available/gust
  notify:
    - restart nginx
- name: enable gust config
  command: ln -s /etc/nginx/sites-available/gust /etc/nginx/sites-enabled/gust creates=/etc/nginx/sites-enabled/gust
